// levels.js — the 7 MVP level definitions, as plain data (a JS module so it
// loads from file:// without fetch/CORS issues during dev).
//
// Each level:
//   unlock   – the command keys the player may press this level (progressive),
//              authored as stock tmux keys; the game maps them to action ids,
//              so the actual playable key follows the player's remap.
//   rewards  – badge tokens shown in the collected-keys tray on completion
//   goal     – { id, ...params } resolved by goals.js
//   objective– one-line goal text for the HUD
//   hint     – longer teaching nudge
//   keys     – chord reference cards beside the play area. Each card lists the
//              ACTION ids it teaches; game.js renders the player's current key
//              for each (or a `keysLabel` override for ranges like 0–9).

import { ARROWS } from './state.js';

export const LEVELS = [
  {
    id: 'panes-1', title: 'Split the World', world: 'Panes',
    blurb: 'Every tmux session begins as a single pane. Time to make room.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['%'],
    rewards: ['%'],
    goal: { id: 'paneCount', count: 2 },
    par: 5,
    objective: 'Split the window into 2 panes.',
    hint: "Hold Ctrl and tap b (that's the prefix), let go, then press % to split into left and right panes.",
    keys: [{ actions: ['split-h'], desc: 'split left / right' }],
  },
  {
    id: 'panes-2', title: "Stack 'Em", world: 'Panes',
    blurb: 'Panes split two ways. Mix a side-by-side split with a stacked one.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['%', '"'],
    rewards: ['"'],
    goal: { id: 'mixedSplit' },
    par: 8,
    objective: 'Make an L-shape: use both % and " (3 panes).',
    hint: '% splits left/right, " splits top/bottom. Split once each way to get three panes in an L.',
    keys: [
      { actions: ['split-h'], desc: 'split left / right' },
      { actions: ['split-v'], desc: 'split top / bottom' },
    ],
  },
  {
    id: 'panes-nav', title: 'Wander', world: 'Panes',
    blurb: "A grid is no use if you can't move. Walk to the far corner.",
    start: { windows: [{ name: 'bash', layout: '2x2' }] },
    unlock: ['%', '"', 'o', ...ARROWS],
    rewards: ['o', 'Arrows'],
    goal: { id: 'activePaneIndex', n: 3 },
    par: 8,
    objective: 'Make pane 3 (bottom-right) the active pane.',
    hint: 'Prefix then an arrow key moves between panes; prefix then o cycles. Land on pane 3 (bottom-right, index 3).',
    keys: [
      { actions: ['pane-left', 'pane-up', 'pane-down', 'pane-right'], desc: 'move to the pane that way' },
      { actions: ['cycle-pane'], desc: 'cycle to the next pane' },
    ],
  },
  {
    id: 'panes-grid', title: 'Four Corners', world: 'Panes',
    blurb: 'Build the classic 2×2 cockpit from a single pane.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['%', '"', 'o', ...ARROWS],
    rewards: ['grid'],
    goal: { id: 'grid2x2' },
    par: 20,
    objective: 'Build a 2×2 grid of 4 equal panes.',
    hint: 'Split left/right, move into one side, then split each side top/bottom. Use arrows or o to move between panes.',
    keys: [
      { actions: ['split-h', 'split-v'], desc: 'split' },
      { actions: ['pane-left', 'pane-up', 'pane-down', 'pane-right', 'cycle-pane'], desc: 'move between panes' },
    ],
  },
  {
    id: 'panes-zoom', title: 'Focus & Destroy', world: 'Panes',
    blurb: 'Too many panes. Clear the clutter, then zoom in to focus.',
    start: { windows: [{ name: 'bash', layout: '2x2' }] },
    unlock: ['%', '"', 'o', ...ARROWS, 'z', 'x'],
    rewards: ['z', 'x'],
    goal: { id: 'zoomedWithCount', count: 2 },
    par: 12,
    objective: 'Kill panes down to 2, then zoom the active one.',
    hint: 'Prefix then x closes the active pane (no confirm here). Get down to 2 panes, then prefix then z zooms the active pane fullscreen.',
    keys: [
      { actions: ['kill-pane'], desc: 'kill the active pane' },
      { actions: ['zoom'], desc: 'zoom / unzoom the active pane' },
    ],
  },
  {
    id: 'panes-q', title: 'By Number', world: 'Panes',
    blurb: 'Arrows step one pane at a time. With q you jump anywhere in one shot.',
    start: { windows: [{ name: 'bash', layout: '2x2' }] },
    unlock: ['q'],
    rewards: ['q'],
    goal: { id: 'activePaneIndex', n: 3 },
    par: 6,
    objective: 'Jump to pane 3 (bottom-right) using pane numbers.',
    hint: 'Prefix then q overlays each pane with its number (0-based, like tmux). Press 3 to jump directly to the bottom-right pane.',
    keys: [
      { actions: ['pane-numbers'], desc: 'show pane numbers, press to jump' },
    ],
  },
  {
    id: 'windows-1', title: 'New Horizons', world: 'Windows',
    blurb: 'Panes live inside windows. Open a few more — watch the status bar fill up.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['c', 'n', 'p'],
    rewards: ['c', 'n', 'p'],
    goal: { id: 'windowCount', count: 3 },
    par: 8,
    objective: 'Have 3 windows open.',
    hint: 'Prefix then c creates a new window (see it appear in the green status bar). Make 3 total. n / p step between them.',
    keys: [
      { actions: ['new-window'], desc: 'create a new window' },
      { actions: ['next-window', 'prev-window'], desc: 'next / previous window' },
    ],
  },
  {
    id: 'windows-jump', title: 'Teleport', world: 'Windows',
    blurb: 'Jump straight to a window by number, then give it a name worth remembering.',
    start: { windows: [
      { name: 'bash', layout: 'single' },
      { name: 'vim', layout: 'single' },
      { name: 'bash', layout: 'single' },
    ] },
    unlock: ['c', 'n', 'p', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'w', ','],
    rewards: ['0-9', 'w', ','],
    goal: { id: 'windowNamed', index: 2, name: 'logs' },
    par: 12,
    objective: 'Jump to window 2 and rename it "logs".',
    hint: 'Prefix then 2 jumps straight to window 2. Then prefix then , to rename it — type logs and press Enter.',
    keys: [
      { actions: ['select-window-0'], keysLabel: '0–9', desc: 'jump to window by number' },
      { actions: ['rename-window'], desc: 'rename the current window' },
    ],
  },
  {
    id: 'adv-swap', title: 'Pane Shuffle', world: 'Advanced',
    blurb: 'You can split and kill panes. Now rearrange them — swap without rebuilding.',
    start: { windows: [{ name: 'bash', layout: '2x2' }] },
    unlock: ['{', '}'],
    rewards: ['{', '}'],
    goal: { id: 'activePaneIndex', n: 3 },
    par: 8,
    objective: 'Move the active pane to position 3 (bottom-right) using swaps.',
    hint: '} swaps the active pane with the next one in order; { swaps with the previous (and wraps). From pane 0, one { is enough — it wraps all the way to position 3.',
    keys: [
      { actions: ['swap-pane-prev'], desc: 'swap with previous pane' },
      { actions: ['swap-pane-next'], desc: 'swap with next pane' },
    ],
  },
  {
    id: 'adv-break', title: 'Break Out', world: 'Advanced',
    blurb: 'Sometimes a pane deserves its own window. Promote it with a single command.',
    start: { windows: [{ name: 'bash', layout: 'two-h' }] },
    unlock: ['!'],
    rewards: ['!'],
    goal: { id: 'brokenOut' },
    par: 8,
    objective: 'Break the active pane out into its own window.',
    hint: 'Prefix then ! tears the active pane away from the layout and opens it as a fresh window — the rest of the split stays intact.',
    keys: [
      { actions: ['break-pane'], desc: 'break pane into a new window' },
    ],
  },
  {
    id: 'adv-resize', title: 'Elbow Room', world: 'Advanced',
    blurb: 'A pane isn\'t stuck at 50%. Push its border and claim more screen.',
    start: { windows: [{ name: 'bash', layout: 'two-h' }] },
    unlock: ['M-ArrowLeft', 'M-ArrowRight'],
    rewards: ['M-←'],
    goal: { id: 'paneExpanded' },
    par: 10,
    objective: 'Resize the active pane until it takes up significantly more space.',
    hint: 'After the prefix, hold Alt and tap ← or → to push the border. Three nudges in one direction reach the goal.',
    keys: [
      { actions: ['resize-pane-left', 'resize-pane-right'], desc: 'resize pane left / right' },
    ],
  },
  {
    id: 'adv-chase', title: 'Hot Pursuit', world: 'Advanced',
    blurb: 'A dot keeps darting around the grid. Hunt it down — again and again, fast.',
    start: { windows: [{ name: 'bash', layout: '3x3' }] },
    chase: true,
    unlock: ['o', 'q', ...ARROWS],
    rewards: ['chase'],
    goal: { id: 'caughtDot' },
    par: 4,
    drills: 8,
    objective: 'Move onto the glowing dot. Catch it 8 times.',
    hint: 'The ● marks the target pane. Step with the arrows, or prefix then q and press the number to pounce straight onto it. Every catch sends the dot somewhere new.',
    keys: [
      { actions: ['pane-left', 'pane-up', 'pane-down', 'pane-right'], desc: 'move toward the dot' },
      { actions: ['cycle-pane'], desc: 'cycle to the next pane' },
      { actions: ['pane-numbers'], desc: 'jump by number' },
    ],
  },
  {
    id: 'adv-last', title: 'Quick Switch', world: 'Advanced',
    blurb: 'Jumping by number is precise. Jumping back is instant. Learn the reflex.',
    start: {
      windows: [
        { name: 'bash', layout: 'single' },
        { name: 'vim', layout: 'single' },
        { name: 'logs', layout: 'single' },
      ],
      activeWindowIndex: 1,
      prevWindowIndex: 2,
    },
    unlock: ['l'],
    rewards: ['l'],
    goal: { id: 'activeWindowIs', index: 2 },
    par: 5,
    objective: 'Jump back to the last window you were on (window 2: logs).',
    hint: 'Prefix then l jumps instantly to whichever window you were in before — no number to remember.',
    keys: [
      { actions: ['last-window'], desc: 'jump to last window' },
    ],
  },
  {
    id: 'adv-multi', title: 'Many Hats', world: 'Advanced',
    blurb: 'The real workflow: multiple windows, each with its own split layout. Build it from scratch.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['c', 'n', 'p', '0', '1', '2', 'o', '%', '"', ...ARROWS],
    rewards: ['mastery'],
    goal: { id: 'multiWindowPanes' },
    par: 30,
    drills: 1,
    objective: 'Open 3 windows and split each one (3 windows, each with 2+ panes).',
    hint: 'c opens a new window. Split it with % or ". Use n/p or number keys to hop between windows and split the others.',
    keys: [
      { actions: ['new-window'], desc: 'open a new window' },
      { actions: ['next-window', 'prev-window'], desc: 'next / previous window' },
      { actions: ['select-window-0'], keysLabel: '0–2', desc: 'jump to window by number' },
      { actions: ['split-h', 'split-v'], desc: 'split the current window' },
    ],
  },
  {
    id: 'sess-detach', title: 'Off Duty', world: 'Sessions',
    blurb: 'tmux sessions outlive you. Detach and trust that everything is still running.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['d'],
    rewards: ['d'],
    goal: { id: 'sessionDetached' },
    par: 5,
    objective: 'Detach from the tmux session.',
    hint: 'Prefix then d detaches your client. The session keeps running in the background — windows, panes, and all. Reattach any time with tmux attach.',
    keys: [
      { actions: ['detach'], desc: 'detach from the session' },
    ],
  },
  {
    id: 'sess-rename', title: 'Named', world: 'Sessions',
    blurb: '"main" means nothing. A good session name tells you exactly what you were working on.',
    start: { windows: [{ name: 'bash', layout: 'single' }] },
    unlock: ['$'],
    rewards: ['$'],
    goal: { id: 'sessionNamed', name: 'work' },
    par: 12,
    objective: 'Rename this session to "work".',
    hint: 'Prefix then $ opens a rename prompt. Type the new name and press Enter. The session name appears in the far-left of the status bar.',
    keys: [
      { actions: ['rename-session'], desc: 'rename the session' },
    ],
  },
];
